export const CORE_PERMISSIONS = [
  { key: 'organization.read', description: 'Read organization profile and structure.' },
  { key: 'organization.manage', description: 'Change organization settings and structure.' },
  { key: 'members.read', description: 'Read organization members.' },
  { key: 'members.manage', description: 'Invite, update, suspend and remove members.' },
  { key: 'roles.manage', description: 'Create roles and grant permissions.' },
  { key: 'billing.read', description: 'Read subscription and entitlement information.' },
  { key: 'billing.manage', description: 'Change plans and billing settings.' },
  { key: 'feature_flags.read', description: 'Read enabled feature flags.' },
  { key: 'audit.read', description: 'Read tenant audit logs.' },
  { key: 'api_keys.manage', description: 'Create and revoke tenant API keys.' },

  { key: 'crm.contact.read', description: 'Read CRM contacts.' },
  { key: 'crm.contact.create', description: 'Create CRM contacts.' },
  { key: 'crm.contact.update', description: 'Update CRM contacts.' },
  { key: 'crm.contact.delete', description: 'Delete CRM contacts.' },
  { key: 'crm.company.read', description: 'Read CRM companies.' },
  { key: 'crm.company.create', description: 'Create CRM companies.' },
  { key: 'crm.company.update', description: 'Update CRM companies.' },
  { key: 'crm.company.delete', description: 'Delete CRM companies.' },
  { key: 'crm.lead.read', description: 'Read CRM leads.' },
  { key: 'crm.lead.create', description: 'Create CRM leads.' },
  { key: 'crm.lead.update', description: 'Update CRM leads.' },
  { key: 'crm.lead.delete', description: 'Delete CRM leads.' },
  { key: 'crm.deal.read', description: 'Read CRM deals.' },
  { key: 'crm.deal.create', description: 'Create CRM deals.' },
  { key: 'crm.deal.update', description: 'Update CRM deals.' },
  { key: 'crm.deal.delete', description: 'Delete CRM deals.' },
  { key: 'crm.pipeline.read', description: 'Read CRM pipelines and stages.' },
  { key: 'crm.pipeline.manage', description: 'Configure CRM pipelines and stages.' },
  { key: 'crm.task.read', description: 'Read CRM tasks.' },
  { key: 'crm.task.create', description: 'Create CRM tasks.' },
  { key: 'crm.task.update', description: 'Update CRM tasks.' },
  { key: 'crm.activity.read', description: 'Read CRM activities.' },
  { key: 'crm.activity.create', description: 'Create CRM activities.' },
  { key: 'crm.appointment.read', description: 'Read CRM appointments.' },
  { key: 'crm.appointment.create', description: 'Create CRM appointments.' },
  { key: 'crm.appointment.update', description: 'Update CRM appointments.' },
  { key: 'crm.note.read', description: 'Read CRM notes.' },
  { key: 'crm.note.create', description: 'Create CRM notes.' },
  { key: 'crm.tag.manage', description: 'Manage CRM tags.' },
  { key: 'crm.custom_field.manage', description: 'Manage CRM custom fields.' },
  { key: 'crm.list.manage', description: 'Manage CRM saved lists and segments.' },

  { key: 'communication.inbox.read', description: 'Read unified inbox conversations and messages.' },
  { key: 'communication.message.send', description: 'Send outbound channel messages.' },
  { key: 'communication.conversation.manage', description: 'Assign and change conversation handling mode.' },
  { key: 'communication.channel.manage', description: 'Configure communication channel accounts.' },
  { key: 'communication.template.manage', description: 'Manage message templates.' },
  { key: 'communication.consent.manage', description: 'Manage communication consent records.' },
  { key: 'communication.campaign.manage', description: 'Create and manage communication campaigns.' },

  { key: 'ai.agent.read', description: 'Read AI agents, versions and run history.' },
  { key: 'ai.agent.manage', description: 'Create, version, activate and configure AI agents.' },
  { key: 'ai.agent.run', description: 'Run AI agents for permitted tenant workflows.' },
  { key: 'ai.tool.manage', description: 'Configure governed AI tool policies.' },
  { key: 'ai.approval.read', description: 'Read AI action approval requests.' },
  { key: 'ai.approval.decide', description: 'Approve or reject governed AI actions.' },
  { key: 'ai.knowledge.read', description: 'Read AI knowledge bases and documents.' },
  { key: 'ai.knowledge.manage', description: 'Manage and ingest tenant AI knowledge.' },
  { key: 'ai.usage.read', description: 'Read AI usage, cost and evaluation telemetry.' },
  { key: 'ai.whatsapp.read', description: 'Read AI WhatsApp bindings, jobs and suggestions.' },
  { key: 'ai.whatsapp.manage', description: 'Configure AI WhatsApp handling and send approved AI-assist suggestions.' },
] as const;
